name: Package Python code to Macintosh' executable
on:
  workflow_dispatch:
    inputs:
      chosen_repository:
        description: "Name of the repository to pack"
        required: true
        type: string
      python_file:
        description: "Main Python file's name"
        required: true
        default: 'main.py'
        type: string
      foreign_libraries:
        description: "Foreign libraries used (separate with only `;`)"
        required: false
        default: "pygame-ce"
        type: string
      assets:
        description: "Assets used by code (Format: source:dest;source2:dest2)"
        required: false
        default: ""
        type: string
      icon:
        description: "Relative path to the game's `.icns` file"
        required: true
        default: "Branding/Logo.icns"
        type: string
      final_name:
        description: "What should be the name of the `.app`?"
        required: true
        default: ""
        type: string

jobs:
  build-macos:
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: '10.13'
    steps:
      - name: Pull the repository
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository_owner }}/${{ inputs.chosen_repository }}'
          token: ${{ secrets.ACCESS }}

      - name: Install Universal2 Python 3.10
        run: |
          curl -O https://www.python.org/ftp/python/3.10.11/python-3.10.11-macos11.pkg
          sudo installer -pkg python-3.10.11-macos11.pkg -target /

      - name: Install foreign libraries
        run: |
          python3 -m pip install --upgrade pip --break-system-packages
          DEPS=$(echo "${{ inputs.foreign_libraries }}" | tr ';' ' ')
          python3 -m pip install pyinstaller $DEPS

      - name: Pack as `.app`
        run: |
          ARGS=(--windowed --noconfirm --target-arch universal2)
          ICON="${{ inputs.icon }}"
          if [ -n "$ICON" ] && [ -f "$ICON" ]; then
            ARGS+=("--icon=$ICON")
          fi
          
          if [ -n "${{ inputs.assets }}" ]; then
            IFS=';' read -ra PAIRS <<< "${{ inputs.assets }}"
            for pair in "${PAIRS[@]}"; do
              pair=$(echo "$pair" | xargs)
              if [ -n "$pair" ]; then 
                ARGS+=(--add-data "$pair")
              fi
            done
          fi
          ARGS+=(--name "${{ inputs.final_name }}")
          
          python3 -m PyInstaller "${ARGS[@]}" "${{ inputs.python_file }}"

      - name: Upload `.app`
        uses: actions/upload-artifact@v4
        with:
          name: '${{ inputs.final_name }}'
          path: 'dist/*.app'
